FORMAT: 1A
HOST: http://127.0.0.1:8000

# fill0520 

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/course/]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
        "id": 1,
        "name": "English Zone",
        "description": "Миссия English Zone заключается в том, чтобы помочь людям раскрыть весь их потенциал.",
        "category": "Cat_1",
        "logo": "http://www.answersfrom.com/wp-content/uploads/2011/09/Not-talanted-but-curious.jpg",
        "contacts": [
            {
                "type": "PHONE",
                "value": "0770 792 299"
            },
            {
                "type": "FACEBOOK",
                "value": "https://www.facebook.com/english.zone.kg/"
            },
            {
                "type": "EMAIL",
                "value": "ezone.kg@gmail.com"
            }
        ],
        "branches": [
            {
                "latitude": "42.847971",
                "longtitude": "74.586733",
                "address": "Manas 58/ Aini - right next to the Manas university"
            },
            {
                "latitude": "42.8586017",
                "longtitude": "74.6068425",
                "address": "Бишкек, Юг-2 дом 15а Советская/Горького"
            }
        ]
            },
            {
        "id": 2,
        "name": "Russian Zone",
        "description": "Миссия English Zone заключается в том, чтобы помочь людям раскрыть весь их потенциал.",
        "category": "Cat_1",
        "logo": "http://www.answersfrom.com/wp-content/uploads/2011/09/Not-talanted-but-curious.jpg",
        "contacts": [
            {
                "type": "PHONE",
                "value": "0770 792 299"
            },
            {
                "type": "FACEBOOK",
                "value": "https://www.facebook.com/english.zone.kg/"
            },
            {
                "type": "EMAIL",
                "value": "ezone.kg@gmail.com"
            }
        ],
        "branches": [
            {
                "latitude": "42.847971",
                "longtitude": "74.586733",
                "address": "Manas 58/ Aini - right next to the Manas university"
            },
            {
                "latitude": "42.8586017",
                "longtitude": "74.6068425",
                "address": "Бишкек, Юг-2 дом 15а Советская/Горького"
            }
        ]
            }
        ]

### Create a New Course [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

         {

            "name": "Moderator",
            "description": "des",
            "category": "Sample",
            "logo": "logo",
            "contacts": [
            {
            "type": "PHONE",
            "value": "228322"
            }
                        ],
        "branches": [
        {
            "latitude": "123",
            "longtitude": "321",
            "address": "Fat street"
        }
                    ]
        }
        
+ Response 201 (application/json)

    + Headers

            Location: /course/course_id

    + Body

            {
            "id": 1,
            "name": "English Zone",
            "description": "Миссия English Zone заключается в том, чтобы помочь людям раскрыть весь их потенциал.",
            "category": "Cat_1",
            "logo": "http://www.answersfrom.com/wp-content/uploads/2011/09/Not-talanted-but-curious.jpg",
            "contacts": [
            {
            "type": "PHONE",
            "value": "0770 792 299"
            },
            {
            "type": "FACEBOOK",
            "value": "https://www.facebook.com/english.zone.kg/"
            },
            {
            "type": "EMAIL",
            "value": "ezone.kg@gmail.com"
            }
                        ],
            "branches": [
            {
            "latitude": "42.847971",
            "longtitude": "74.586733",
            "address": "Manas 58/ Aini - right next to the Manas university"
            },
            {
            "latitude": "42.8586017",
            "longtitude": "74.6068425",
            "address": "Бишкек, Юг-2 дом 15а Советская/Горького"
            }
                        ]
            }