# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default=b'', max_length=100)),
                ('description', models.TextField()),
                ('category', models.TextField()),
                ('logo', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
