# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181014_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[(b'email', b'EMAIL'), (b'fb', b'FACEBOOK'), (b'phone', b'PHONE')], default=b'PHONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
