# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181014_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imgpath', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='branch',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='courses.Category'),
        ),
    ]
